library(shiny)
shinyUI(fluidPage(
    titlePanel("Segmented Linear Regression"),
    sidebarLayout(
    sidebarPanel(
        fileInput("uploaded","Place your data here",accept="text/csv"),
        uiOutput("selectResponse"),
        uiOutput("selectPredictor"),
        uiOutput("kinkSlider"),
        uiOutput("times10"),
        helpText("For program documentation, see 'Help' tab",
                 br(), br(),
                 "Sample data comes from: ",
                 br(),
                 a("Mann, Michael E.; Bradley, Raymond S.; Hughes, Malcolm K. (1999), ", 
                   "Northern hemisphere temperatures during the past millennium: ", 
                   "Inferences, uncertainties, and limitations, ", 
                   "Geophysical Research Letters 26 (6): 759-762", 
                   href="http://www.meteo.psu.edu/holocene/public_html/shared/research/old/mbh99.html"))
    ),
    mainPanel(
        withMathJax(), 
        tabsetPanel(type = "tabs", 
            tabPanel("Plot", plotOutput("scatterPlot")), 
            tabPanel("Model", h3("$$ Y_i = \\beta_0 + \\beta_1 X_i + \\sum_{k=1}^d \\gamma_k (X_i - \\xi_k)_+ + \\epsilon_i $$"), 
                     verbatimTextOutput("linearModel"), plotOutput("residualPlot")), 
            tabPanel("Data", dataTableOutput("table")),
            tabPanel("Help", 
                     helpText("This App is created to make Segmented Linear Regression ", 
                                "(also known as broken-stick regression) easy and intuitive ", 
                                "for users with little background in R programming. ",
                                "Using a slider UI, user can dynamically control position of ", 
                                "the knot point and see how the fitted line respond ", 
                                "as well as change in the goodness of fit. ", 
                                br(),br(),
                                "Here's what you need to get started", 
                                br(),br(),
                                "Step 1: ",
                                br(),
                                "Upload data in the form of CSV making sure a header row is included",
                                br(),br(),
                                "Step 2: ",
                                br(),
                                "Select the response and predictor variable",
                                br(),br(),
                                "Step 3: ",
                                br(),
                                "A scatter plot of predictor vs response is automatically generated",
                                br(),br(),
                                "Step 4: ",
                                br(),
                                "Adjust the position of the knot point using the slider. ", 
                                "Finer control can be achieved with the X10 zoom slider. " , 
                                "User do not need to worry whether the slider covers the entire range of ", 
                                "the X-variable as this is has been taken care of by the program in the background.",
                                br(),br(),
                                "Step 5: ",
                                br(),
                                "R-square is reflected at the top left of the plot so user ", 
                                "can see when an optimum fit has been found"))
        )
    )
    )
))